pipeline {
    agent any

    tools {
        maven 'MAVEN_HOME'
        jdk 'JAVA_HOME'
    }

    parameters {
        choice(name: 'BROWSER', choices: ['chrome', 'firefox', 'edge'], description: 'Select browser')
        booleanParam(name: 'HEADLESS', defaultValue: true, description: 'Run tests in headless mode')
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/screamingbazz/tenmay.git'
            }
        }

        stage('Clean Build') {
            steps {
                bat 'mvn clean'
            }
        }

        stage('Run Tests') {
            steps {
                bat "mvn test -Dbrowser=%BROWSER% -Dheadless=%HEADLESS%"
            }
        }

        stage('Generate Reports') {
            steps {
                echo "Reports should be generated by Maven/TestNG framework"
            }
        }
    }

    post {

        always {
            archiveArtifacts artifacts: 'target/**', fingerprint: true
        }

        success {
            echo 'Tests Passed Successfully'
        }

        failure {
            echo 'Tests Failed - Check logs'
        }
    }
}
